kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.customerName }}
  name: allow-inter-namespace
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app }}
      cust: {{ .Values.customerName }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.app }}
              cust: {{ .Values.customerName }}
      ports: []