{{- if .Values.linkerd.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.customerName }}
  name: allow-linkerd
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: linkerd
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: linkerd-viz
{{- end }}