{{- if .Values.secrets.useSecretsStoreCSI }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "dotcms.secret.provider.className" . }}
  namespace: {{ .Values.customerName }}
  labels:
    app.dotcms.cloud/aws-region: {{ .Values.aws.region }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.aws.secrets.secretsArn }}"
        jmesPath:
            {{- range $group, $config := .Values.secrets.sync.shared }}
            {{- range $key := $config.keys }}
            - path: '"{{ $group }}{{- if eq $group "license" }}"'{{- else }}-{{ $key }}"'{{- end }}
              objectAlias: {{ $group }}{{- if eq $group "license" }}{{- else }}-{{ $key }}{{- end }}
            {{- end }}
            {{- end }}
            {{- range $envName := keys .Values.environments }}
            {{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
            {{- range $group, $config := $.Values.secrets.sync.env }}
            {{- range $key := $config.keys }}
            - path: '"{{ $envName }}-{{ $group }}-{{ $key }}"'
              objectAlias: {{ $envName }}-{{ $group }}-{{ $key }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
  secretObjects:
    # Shared secrets
    {{- range $group, $config := .Values.secrets.sync.shared }}
    - secretName: {{ include "dotcms.secret.shared.name" (dict "Values" $.Values "secretName" $group ) }}
      type: {{ $config.type }}
      data:
      {{- range $key := $config.keys }}
        - key: {{ $key }}
          objectName: {{ $group }}{{- if eq $group "license" }}{{- else }}-{{ $key }}{{- end }}
      {{- end }}
    {{- end }}
    {{- range $group, $config := $.Values.secrets.sync.env }}
    {{- range $envName := keys $.Values.environments }}
    {{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
    - secretName: {{ include "dotcms.secret.env.name" (dict "Values" .Values "secretName" $group ) }}
      type: {{ $config.type }}
      data:
      {{- range $key := $config.keys }}
        - key: {{ $key }}
          objectName: {{ $envName }}-{{ $group }}-{{ $key }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}