{{- if .Values.redis.local.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.customerName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.local.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          command: ["redis-server", "--requirepass", "{{ .Values.redis.password }}"]
{{- end }}