{{- if .Values.dotcms.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.fullname }}
spec:
  replicas: 1
  serviceName: {{ .Values.fullname }}
  selector:
    matchLabels:
      app: {{ .Values.fullname }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullname }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: dotcms
          image: dotcms/dotcms:{{ .Values.version }}
          ports:
            - containerPort: 8082
            - containerPort: 8443
          env:
            - name: CMS_JAVA_OPTS
              value: '-Xmx1g'
            - name: LANG
              value: 'C.UTF-8'
            - name: TZ
              value: 'UTC'
            - name: TOMCAT_REDIS_SESSION_ENABLED
              value: '{{ .Values.redis.sessionEnabled }}'
            - name: TOMCAT_REDIS_SESSION_HOST
              value: '{{ .Values.redis.sessionHost }}'
            - name: TOMCAT_REDIS_SESSION_PORT
              value: '{{ .Values.redis.port }}'
            - name: TOMCAT_REDIS_SESSION_PASSWORD
              value: '{{ .Values.redis.password }}'
            - name: TOMCAT_REDIS_SESSION_SSL_ENABLED
              value: '{{ .Values.redis.sslEnabled }}'
            - name: TOMCAT_REDIS_SESSION_PERSISTENT_POLICIES
              value: '{{ .Values.redis.persistentPolicies }}'
            - name: DB_BASE_URL
              value: 'jdbc:postgresql://db/{{ .Values.database.name }}'
            - name: DB_USERNAME
              value: '{{ .Values.database.username }}'
            - name: DB_PASSWORD
              value: '{{ .Values.database.password }}'
            - name: DOT_DOTCMS_CLUSTER_ID
              value: '{{ .Values.clusterID }}'              
            - name: DOT_ES_ENDPOINTS
              value: 'http://opensearch:{{ .Values.opensearch.port }}'

            # Custom environment variables
            {{- range $key, $value := .Values.dotcms.customEnvVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}            
          volumeMounts:
            - name: shared-volume
              mountPath: /data/shared
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: dotcms-pvc
{{- end }}