{{- range $envName := keys .Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{- $fullName := include "dotcms.env.fullName" . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.customerName }}-{{ .Values.environment }}-alb
  namespace: {{ .Values.customerName }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.type }}
    service.beta.kubernetes.io/aws-load-balancer-internal: 'false'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: dotcms.client.name.short={{ .Values.customerName }}, VantaOwner=example@dotcms.com, VantaDescription=ALB for {{ .Values.customerName }} {{ .Values.environment }}, VantaNonProd=true
    alb.ingress.kubernetes.io/backend-protocol: {{ dig "ingress" "alb" "healthcheck" "backendProtocol" "HTTP" .Values }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ dig "ingress" "alb" "healthcheck" "protocol" "HTTP" .Values }}
    alb.ingress.kubernetes.io/healthcheck-port: '{{ .Values.readinessProbe.httpGet.port }}'
    alb.ingress.kubernetes.io/healthcheck-path: '{{ .Values.readinessProbe.httpGet.path }}'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '{{ dig "ingress" "alb" "healthcheck" "intervalSeconds" "10" .Values }}'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '{{ dig "ingress" "alb" "healthcheck" "timeoutSeconds" "5" .Values }}'
    alb.ingress.kubernetes.io/success-codes: '{{ dig "ingress" "alb" "healthcheck" "successCodes" "200" .Values }}'
    alb.ingress.kubernetes.io/healthy-threshold-count: '{{ dig "ingress" "alb" "healthcheck" "healthyThresholdCount" "3" .Values }}'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '{{ dig "ingress" "alb" "healthcheck" "unhealthyThresholdCount" "2" .Values }}'
    alb.ingress.kubernetes.io/target-group-attributes: >-
      stickiness.enabled={{ dig "ingress" "alb" "targetGroup" "stickiness" "enabled" true .Values }},
      stickiness.lb_cookie.duration_seconds={{ dig "ingress" "alb" "targetGroup" "stickiness" "cookieDuration" "18000" .Values }},
      slow_start.duration_seconds={{ dig "ingress" "alb" "targetGroup" "slowStart" "durationSeconds" "120" .Values }},
      deregistration_delay.timeout_seconds={{ dig "ingress" "alb" "targetGroup" "deregistrationDelay" "timeoutSeconds" "60" .Values }},
      load_balancing.algorithm.type={{ dig "ingress" "alb" "targetGroup" "loadBalancing" "algorithmType" "least_outstanding_requests" .Values }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    {{- if eq .Values.ingress.type "alb" }}
    {{- include "dotcms.ingress.alb.annotations" . | nindent 4 }}
    {{- end }}
spec:
  {{- if eq .Values.ingress.type "nginx" }}
  tls:
    - hosts:
        - {{ include "dotcms.ingress.externalHost" . | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  ingressClassName: {{ .Values.ingress.type }}
  rules:
    {{ include "dotcms.ingress.alb.additionalHosts" . | nindent 4 }}
    - host: {{ include "dotcms.ingress.externalHost" . | quote }}
    - http:
        paths:
          - backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
            path: /
            pathType: Prefix
          - backend:
              service:
                name: {{ include "dotcms.env.serviceName" . }}
                port:
                  number:
                    8082
            path: /
            pathType: Prefix
  defaultBackend:
    service:
      name: {{ include "dotcms.env.serviceName" . }}
      port:
        number: 8082
{{- end }}
{{- end }}