apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fullname }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  # Explicitly specify the ingressClassName
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.fullname }}-svc
                port:
                  number: {{ .Values.dotcms.port }}
  # Add a default backend
  defaultBackend:
    service:
      name: {{ .Values.fullname }}-svc
      port:
        number: {{ .Values.dotcms.port }}
