{{- if .Values.coreServiceEnabled }}
{{- range $envName := keys $.Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{- $fullName := include "dotcms.env.fullName" . }}
{{- $namespace := .Values.customerName }}
{{- $configMapName := printf "%s-%s-upgrade-metadata" .Values.customerName .Values.environment }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dotcms.postUpgradeJobName" . }}
  namespace: {{ .Values.customerName }}
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 7200
  template:
    spec:
      serviceAccountName: {{ include "dotcms.serviceaccount" . }}
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking for ConfigMap {{ $configMapName }} in namespace {{ $namespace }}..."

              # Check if ConfigMap exists
              if kubectl get configmap {{ $configMapName }} -n {{ $namespace }} > /dev/null 2>&1; then
                echo "ConfigMap found. Fetching replica count..."
                REPLICAS=$(kubectl get configmap {{ $configMapName }} \
                  -o jsonpath='{.data.replicas}' -n {{ $namespace }})

                echo "Scaling up statefulset {{ $fullName }} to $REPLICAS replicas..."
                kubectl scale statefulset {{ $fullName }} --replicas=$REPLICAS -n {{ $namespace }}

                # Wait for the deployment to scale up
                kubectl rollout status statefulset {{ $fullName }} -n {{ $namespace }}

              else
                echo "No ConfigMap found for {{ $envName }}. Scale down was not enabled. Skipping post-upgrade scaling."
              fi
      restartPolicy: Never
{{- end }}
{{- end }}
{{- end }}
