# templates/hooks/post-upgrade-scale.yaml
{{- if .Values.dotcms.enabled }}
{{- range $envName := keys .Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{- $fullName := include "dotcms.env.fullName" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dotcms.postUpgradeJobName" . }}
  namespace: {{ .Values.customer_name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: {{ include "dotcms.serviceaccount" . }}
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking for ConfigMap {{ .Values.customer_name }}-{{ $envName }}-scale-data in namespace {{ .Values.customer_name }}..."

              # Check if ConfigMap exists
              if kubectl get configmap {{ .Values.customer_name }}-{{ $envName }}-scale-data -n {{ .Values.customer_name }} > /dev/null 2>&1; then
                echo "ConfigMap found. Fetching replica count..."
                REPLICAS=$(kubectl get configmap {{ .Values.customer_name }}-{{ $envName }}-scale-data \
                  -o jsonpath='{.data.replicas}' -n {{ .Values.customer_name }})

                echo "Scaling up statefulset {{ .Values.customer_name }}-{{ $envName }} to $REPLICAS replicas..."
                kubectl scale statefulset {{ $fullName }} --replicas=$REPLICAS -n {{ .Values.customer_name }}

                # Wait for the deployment to scale up
                kubectl rollout status statefulset {{ $fullName }} -n {{ .Values.customer_name }}

                echo "Cleaning up ConfigMap..."
                kubectl delete configmap {{ .Values.customer_name }}-{{ $envName }}-scale-data -n {{ .Values.customer_name }}
              else
                echo "No ConfigMap found for {{ $envName }}. Scale down was not enabled. Skipping post-upgrade scaling."
              fi
      restartPolicy: Never
{{- end }}
{{- end }}
{{- end }}
