{{- if .Values.coreServiceEnabled }}
{{- range $envName := keys $.Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{ $pvName := include "dotcms.volume.shared.pv" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dotcms.volume.shared.pvc" . }}
spec:
  accessModes:
  - ReadWriteMany
  {{- if and (eq .Values.cloudProvider "aws") (not (empty .Values.volumes.shared.volumeHandle)) }}
  volumeName: {{ $pvName }}
  {{- end }}
  storageClassName: {{ include "dotcms.storageClassName" . }}
  resources:
    requests:
      storage: 30Gi # This is an arbitrary number due to EFS not imposing any limitations but the field is mandatory for Kubernetes   
{{- if and (eq .Values.cloudProvider "aws") (not (empty .Values.volumes.shared.volumeHandle)) .Values.volumes.shared.create }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.customerName }}
  name: {{ $pvName }}
spec:
  capacity:
    storage: 30Gi # This is an arbitrary number due to EFS not imposing any limitations but the field is mandatory for Kubernetes
  volumeMode: Filesystem
  mountOptions:
    - accesspoint={{ required "The value for volumes.shared.accessPoint is required but not provided." .Values.volumes.shared.accessPoint }} # Mount options, if applicable
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "dotcms.storageClassName" . }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ required "The value for volumes.shared.volumeHandle is required but not provided." .Values.volumes.shared.volumeHandle }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.database.local.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dotcms.volume.shared.local" (dict "Values" $.Values "type" "db") }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ include "dotcms.storageClassName" . }}
  resources:
    requests:
      storage: 30Gi # This is an arbitrary number due to EFS not imposing any limitations but the field is mandatory for Kubernetes
{{- end }}
---
{{- if .Values.opensearch.local.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dotcms.volume.shared.local" (dict "Values" $.Values "type" "opensearch") }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ include "dotcms.storageClassName" . }}
  resources:
    requests:
      storage: 30Gi # This is an arbitrary number due to EFS not imposing any limitations but the field is mandatory for Kubernetes
{{- end }}
