# templates/rbac.yaml
{{- if .Values.coreServiceEnabled }}
{{- range $envName := keys $.Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.customerName }}-{{ $envName }}-hook-role
  namespace: {{ .Values.customerName }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-10"    
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.customerName }}-{{ $envName }}-hook-rolebinding
  namespace: {{ .Values.customerName }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-10"    
subjects:
  - kind: ServiceAccount
    name: {{ include "dotcms.serviceaccount" . }}
    namespace: {{ .Values.customerName }}
roleRef:
  kind: Role
  name: {{ .Values.customerName }}-{{ $envName }}-hook-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}