{{- if .Values.dotcms.enabled }}
{{- range $envName := keys .Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{- $fullName := include "dotcms.env.fullName" . }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.customer_name }}
  name: {{ include "dotcms.env.serviceName" . }}
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: NodePort
  selector:
    fullname: {{ $fullName }}
{{- end }}
{{- end }}
{{- end }}