---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "dotcms.serviceaccount" . }}
  namespace: {{ .Values.customer_name }}
  annotations:
    {{- if eq .Values.cloud_provider "aws" }}
    eks.amazonaws.com/role-arn: {{ required "A valid .Values.aws.serviceAccount.roleArn is required when cloud_provider is aws" .Values.aws.serviceAccount.roleArn }}
    {{- end }}
