{{- if .Values.dotcms.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.fullname }}-svc
spec:
  selector:
    app: {{ .Values.fullname }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
{{- end }}