{{- if .Values.coreServiceEnabled }}
{{- range $envName := keys .Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{- $fullName := include "dotcms.env.fullName" . }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.customerName }}
  name: {{ include "dotcms.env.serviceName.pp" . }}
spec:
  selector:
    fullname: {{ $fullName }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
{{- end }}
{{- end }}
{{- end }}