---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "dotcms.serviceaccount.app" . }}
  namespace: {{ .Values.customerName }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-50"
    {{- if eq .Values.cloudProvider "aws" }}
    eks.amazonaws.com/role-arn: {{ required "A valid .Values.aws.serviceAccount.roleArn is required when cloudProvider is aws" .Values.aws.serviceAccount.roleArn }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dotcms.serviceaccount.admin" . }}
  namespace: {{ .Values.customerName }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-50"