---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "dotcms.serviceaccount" . }}
  namespace: {{ .Values.customerName }}
  annotations:
    {{- if eq .Values.cloudProvider "aws" }}
    eks.amazonaws.com/role-arn: {{ required "A valid .Values.aws.serviceAccount.roleArn is required when cloudProvider is aws" .Values.aws.serviceAccount.roleArn }}
    {{- end }}
