{{- if .Values.coreServiceEnabled }}
{{- range $envName := keys .Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{- $fullName := include "dotcms.env.fullName" . }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.customerName }}
  name: {{ include "dotcms.env.serviceName" . }}
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
    {{- if or ($.Values.management.enabled | default false) ($.Values.prometheus.enabled | default false) }}
    - name: management
      port: {{ $.Values.management.port }}
      targetPort: {{ $.Values.management.port }}
      protocol: TCP
    {{- end }}
  type: NodePort
  selector:
    fullname: {{ $fullName }}
{{- end }}
{{- end }}
{{- end }}