{{- if .Values.opensearch.local.enabled }}
{{- $fullName := include "dotcms.opensearch.fullName" . }}
{{- $namespace := .Values.customerName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-20"  
  labels:
    app: {{ $fullName }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: metrics
      port: 9600
      targetPort: 9600
      protocol: TCP
  selector:
    app: {{ $fullName }}

{{- end }}