{{- if .Values.coreServiceEnabled }}
{{- range $envName := keys $.Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{- $fullName := include "dotcms.env.fullName" . }}
{{- $dbName := include "dotcms.db.name" . }}
{{- $baseUrl := printf "jdbc:postgresql://%s:%v/%s?ssl.mode=prefer" .Values.database.host ( int .Values.database.port ) $dbName  }}
{{- $namespace := .Values.customerName }}
{{- $licenseSecretName := include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "license") }}
{{- $licenseSecretExists := ne (lookup "v1" "Secret" $namespace $licenseSecretName) nil }}
{{- $useLicense := default (or $licenseSecretExists .Values.license) .Values.useLicense }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ include "dotcms.name.customer" . }}
  name: {{ $fullName }}
  labels:
    {{- if eq $.Values.cloudProvider "aws" }}
    app.dotcms.cloud/aws-region: {{ $.Values.aws.region }}
    {{- end }}
    app.kubernetes.io/instance: {{ $.Values.customerName }}
spec:
  selector:
    matchLabels:
      app: {{ $.Values.app }}
      fullname: {{ $fullName }}
  serviceName: {{ $fullName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        {{- if $.Values.linkerd.enabled }}
        linkerd.io/inject: enabled
        {{- end }}
      labels:
        app: {{ $.Values.app }}
        env: {{ .Values.environment }}
        ver: {{ .Values.environment }}
        cust: {{ $.Values.customerName }}
        fullname: {{ $fullName }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: dotcms
          image: {{ include "dotcms.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: '{{ .Values.resources.requests.cpu }}'
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: '{{ .Values.resources.limits.cpu }}'
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: CMS_JAVA_OPTS
              value: "-Xmx{{ .Values.javaHeapMax }} {{ .Values.defaultJavaOpts }} {{ .Values.additionalJavaOpts }}"
            - name: DOT_ES_ENDPOINTS
              value: "{{ include "dotcms.opensearch.endpoints" . }}"
            - name: DOT_ES_AUTH_TYPE
              value: {{ $.Values.opensearch.auth.type }}
            - name: DOT_ES_AUTH_BASIC_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "elasticsearch") }}
                  key: username
            - name: DOT_ES_AUTH_BASIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "elasticsearch") }}
                  key: password
            - name: DB_DNSNAME
              value: {{ $.Values.database.host }}
            - name: DB_BASE_URL
              value: {{ $baseUrl }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "dotcms.secret.env.name" (dict "Values" .Values "secretName" "database") }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: {{ include "dotcms.secret.env.name" (dict "Values" .Values "secretName" "database") }}
                    key: password
            {{- if $useLicense }}
            - name: LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "license") }}
                  key: license
            {{- end }}
            - name: DOT_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dotcms.secret.env.name" (dict "Values" .Values "secretName" "dotcms-admin") }}
                  key: password
            - name: DOT_ARCHIVE_IMPORTED_LICENSE_PACKS
              value: 'false'
            - name: DOT_REINDEX_THREAD_MINIMUM_RUNTIME_IN_SEC
              value: '120'
            - name: DOT_DOTGENERATED_DEFAULT_PATH
              value: shared
            - name: DOT_DOTCMS_CLUSTER_ID
              value: {{ include "dotcms.opensearch.cluster" . }}
            - name: DOT_REINDEX_THREAD_ELASTICSEARCH_BULK_SIZE
              value: '5'
            - name: DOT_REINDEX_THREAD_ELASTICSEARCH_BULK_ACTIONS
              value: '1'
            - name: DOT_REINDEX_RECORDS_TO_FETCH
              value: '10'
            - name: DOT_SYSTEM_STATUS_API_IP_ACL
              value: 0.0.0.0/0
            {{- if eq $.Values.cloudProvider "aws" }}
            - name: DOT_REMOTE_CALL_SUBNET_BLACKLIST
              value: {{ .Values.remoteCallSubnetBlacklist }}
            {{- end }}
            - name: DOT_REMOTE_CALL_ALLOW_REDIRECTS
              value: 'true'
            - name: DOT_URI_NORMALIZATION_FORBIDDEN_REGEX
              value: \/\/html\/.*
            - name: DOT_COOKIES_HTTP_ONLY
              value: 'true'
            - name: COOKIES_SECURE_FLAG
              value: always
            - name: CACHE_CATEGORYPARENTSCACHE_SIZE
              value: '25000'
            - name: CACHE_CONTENTLETCACHE_SIZE
              value: '15000'
            - name: CACHE_H22_RECOVER_IF_RESTARTED_IN_MILLISECONDS
              value: '60000'
            - name: DOT_CACHE_GRAPHQLQUERYCACHE_SECONDS
              value: '1200'
            - name: DOT_ENABLE_SYSTEM_TABLE_CONFIG_SOURCE
              value: 'false'
            {{- if $.Values.telemetry.enabled }}
            - name: DOT_FEATURE_FLAG_TELEMETRY
              value: 'true'
            - name: DOT_TELEMETRY_SAVE_SCHEDULE
              value: 0 0 */8 * * ?
            - name: DOT_TELEMETRY_CLIENT_CATEGORY
              value: {{ .Values.telemetry.telemetryClient | quote }}
            {{- end }}
            - name: TOMCAT_REDIS_SESSION_ENABLED
              value: '{{ .Values.redisSessions.enabled }}'
            {{- if .Values.redisSessions.enabled }}
            - name: TOMCAT_REDIS_SESSION_HOST
              value: '{{ $.Values.redis.sessionHost }}'
            - name: TOMCAT_REDIS_SESSION_PORT
              value: '{{ $.Values.redis.port }}'
            - name: TOMCAT_REDIS_SESSION_PASSWORD
              value: '{{ $.Values.redis.password }}'
            - name: TOMCAT_REDIS_SESSION_SSL_ENABLED
              value: '{{ $.Values.redis.sslEnabled }}'
            - name: TOMCAT_REDIS_SESSION_PERSISTENT_POLICIES
              value: '{{ $.Values.redis.sessionPersistentPolicies }}'
            {{- end }}
            {{- if .Values.mail.enabled }}
            - name: DOT_MAIL_SMTP_HOST
              value: '{{ $.Values.mail.host }}'
            - name: DOT_MAIL_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "ses") }}
                  key: username
            - name: DOT_MAIL_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "ses") }}
                  key: password
            {{- end }}
            # Custom environment variables
            {{- range $key, $value := .Values.envVariables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
          - containerPort: 8080
            name: api
          - containerPort: 8081
            name: web-insecure
          - containerPort: 8082
            name: web-secure
          - containerPort: 5701
            name: hazelcast
          lifecycle:
            postStart:
              {{- if $useLicense }}
              exec:
                command: # This functionality should be moved to core.
                  - /bin/sh
                  - -c
                  - |
                    mkdir -p /data/shared/assets
                    echo "$LICENSE" | base64 -d > /data/shared/assets/license.zip
              {{- end }}
            preStop:
              exec:
                command:
                  - sleep
                  - '20'
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.httpGet.path }}
              port: {{ .Values.startupProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          volumeMounts:
            - name: dotcms-shared
              mountPath: /data/shared
            {{- if .Values.secrets.useSecretsStoreCSI }}
            - mountPath: /mnt/{{ include "dotcms.secret.provider.className" .  }}
              name: {{ include "dotcms.secret.provider.className" .  }}
              readOnly: true
            {{- end }}
      {{- if .Values.affinity.requireDifferentHosts }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: fullname
                    operator: In
                    values:
                      - {{ $fullName }}
              topologyKey: kubernetes.io/hostname
        {{- end }}
      volumes:
      - name: dotcms-shared
        persistentVolumeClaim:
          claimName: {{ include "dotcms.pvc.env.name" . }}
      {{- if .Values.secrets.useSecretsStoreCSI }}
      - name: {{ include "dotcms.secret.provider.className"  . }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "dotcms.secret.provider.className" .  }}
      {{- end }}
      serviceAccountName: {{ include "dotcms.serviceaccount" .  }}

{{- end }}

{{- end }}
{{- end }}
