{{- if .Values.coreServiceEnabled }}
{{- range $envName := keys $.Values.environments }}
{{- with include "myapp.mergeEnvironment" ( mergeOverwrite $ (dict "envName" $envName )) | fromYaml }}
{{- $fullName := include "dotcms.env.fullName" . }}
{{- $dbName := include "dotcms.db.name" . }}
{{- $baseUrl := printf "jdbc:postgresql://%s:%v/%s?ssl.mode=prefer" .Values.database.host ( int .Values.database.port ) $dbName  }}
{{- $namespace := .Values.customerName }}
{{- $licenseSecretName := include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "license") }}
{{- $licenseSecretExists := ne (lookup "v1" "Secret" $namespace $licenseSecretName) nil }}
{{- $useLicense := default (or $licenseSecretExists .Values.license) .Values.useLicense }}
{{- $configMapMetadata := printf "%s-%s-upgrade-metadata" .Values.customerName .Values.environment }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ include "dotcms.name.customer" . }}
  name: {{ $fullName }}
  labels:
    {{- if eq $.Values.cloudProvider "aws" }}
    app.dotcms.cloud/aws-region: {{ $.Values.aws.region }}
    {{- end }}
    app.kubernetes.io/instance: {{ $.Values.customerName }}
spec:
  selector:
    matchLabels:
      app: {{ $.Values.app }}
      fullname: {{ $fullName }}
  serviceName: {{ $fullName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        {{- if $.Values.linkerd.enabled }}
        linkerd.io/inject: enabled
        {{- end }}
      labels:
        app: {{ $.Values.app }}
        env: {{ .Values.environment }}
        ver: {{ .Values.environment }}
        cust: {{ $.Values.customerName }}
        fullname: {{ $fullName }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
        - name: wait-for-job
          image: groundnuty/k8s-wait-for:no-root-v1.7
          imagePullPolicy: IfNotPresent
          args:
            - job
            - {{ include "dotcms.preUpgradeJobName" . }}-{{ .Release.Revision }}

        {{- if .Values.database.local.enabled }}
        - name: wait-for-db
          image: bitnami/kubectl:1.32.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for DB to be ready..."
              kubectl wait --for=condition=Ready pod -l app=db -n {{ $namespace }} --timeout=300s
              echo "DB is ready."            
        {{- end }}
        
        - name: check-backup-restore
          image: bitnami/kubectl:1.32.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [ -f /tmp/backupRestore ]; then
                rm /tmp/backupRestore
              fi

              echo "Checking backup/restore operation status from ConfigMap {{ $configMapMetadata }} in namespace {{ $namespace }}..."
              BACKUP_RESTORE_ENABLED=$(kubectl get configmap {{ $configMapMetadata }} -n {{ $namespace }} -o=jsonpath='{.data.backupRestoreEnabled}' 2>/dev/null || echo "false")

              if [ "$BACKUP_RESTORE_ENABLED" == "true" ]; then
                echo "true" > /tmp/backupRestore
              else
                echo "Backup/Restore operation not detected. Skipping container"
              fi
          volumeMounts:
            - name: admin-shared-{{ $envName }}
              mountPath: /tmp

        - name: check-upgrade
          image: bitnami/kubectl:1.32.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [ -f /tmp/skip ]; then
                rm /tmp/skip
              fi
              echo "Checking upgrade status from ConfigMap {{ $configMapMetadata }} in namespace {{ $namespace }}..."
              UPGRADE_REQUIRED=$(kubectl get configmap {{ $configMapMetadata }} -n {{ $namespace }} -o=jsonpath='{.data.upgradeRequired}' 2>/dev/null || echo "false")
              echo "Upgrade required value: $UPGRADE_REQUIRED"
              if [ "$UPGRADE_REQUIRED" != "true" ]; then
                echo "Upgrade not required. Marking skip..."
                echo "skip" > /tmp/skip                   
              fi            
          volumeMounts:
            - name: admin-shared-{{ $envName }}
              mountPath: /tmp

        - name: dotcms-upgrade      
          {{- include "dotcms.container.spec" (merge (dict "IsUpgradeJob" true "EnableProbes" false "ShutdownOnStartupValue" true "UseLicense" $useLicense) .) | nindent 10 }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [ -f /tmp/skip ]; then
                echo "Upgrade not required. Skipping container execution."
              else
                echo "Upgrade required. Launching original entrypoint..."
                echo "env DOT_SHUTDOWN_ON_STARTUP=$DOT_SHUTDOWN_ON_STARTUP"
                exec /srv/entrypoint.sh dotcms
              fi
              exit 0

      containers:
        - name: dotcms
          {{- include "dotcms.container.spec" (merge (dict "IsUpgradeJob" false "EnableProbes" true "ShutdownOnStartupValue" false "useLicense" $useLicense) .) | nindent 10 }}
      {{- if .Values.affinity.requireDifferentHosts }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: fullname
                    operator: In
                    values:
                      - {{ $fullName }}
              topologyKey: kubernetes.io/hostname
        {{- end }}
      volumes:
      - name: admin-shared-{{ $envName }}
        emptyDir: {}
      - name: dotcms-shared
        persistentVolumeClaim:
          claimName: {{ include "dotcms.pvc.env.name" . }}
      - name: backup-volume-{{ $envName }}
        hostPath:
          path: {{ .Values.hostPath }}
          type: DirectoryOrCreate          
      {{- if .Values.secrets.useSecretsStoreCSI }}
      - name: {{ include "dotcms.secret.provider.className"  . }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "dotcms.secret.provider.className" .  }}
      {{- end }}
      serviceAccountName: {{ include "dotcms.serviceaccount.app" .  }}

{{- end }}

{{- end }}
{{- end }}
