namespace: dotcms-dev
fullname: dotcms-cluster
environment: dev
version: 'latest'
clusterID: dotcms-local-dev-cluster

resources:
  requests:
    cpu: 0.5
    memory: 5Gi
  limits:
    cpu: 2
    memory: 5Gi

terminationGracePeriodSeconds: 40
startupDelaySeconds: 30
serviceAccountName: dotcms-sa

ingress:
  tlsSecretName: developer-certificate-secret
  host: dotcms.local
    
dotcms:
  enabled: true
  port: 8080
  image: dotcms/dotcms-test:1.0.0-SNAPSHOT
  imagePullPolicy: Never
  replicaCount: 1
  storageSize: 3Gi
  javaOpts: '-Xmx1G'
  lang: 'C.UTF-8'
  timezone: 'UTC'  
  customEnvVars:
    DOT_ES_AUTH_BASIC_PASSWORD: "admin"
    DOT_INITIAL_ADMIN_PASSWORD: "admin"

  container:
    ports:
      - containerPort: 8082
      - containerPort: 8443  
    lifecycle:
      postStart:
        command:
          - /bin/bash
          - -c
          - if [ ! -d /data/shared/assets/.backup ]; then mkdir /data/shared/assets/.backup;
            fi; ln -s /data/shared/assets/.backup /data/local/dotsecure/backup;
      preStop:
        command:
          - sleep
          - '20'

    startupProbe:
      httpGet:
        path: /api/v1/appconfiguration
        port: 8082
      initialDelaySeconds: 60
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 18
      timeoutSeconds: 1

    livenessProbe:
      httpGet:
        path: /api/v1/appconfiguration
        port: 8082
      initialDelaySeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 1
      timeoutSeconds: 10

    readinessProbe:
      httpGet:
        path: /api/v1/appconfiguration
        port: 8082
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 1
      timeoutSeconds: 5    

redis:
  image: redis:latest
  storageSize: 3Gi
  local: true
  host: redis.local
  password: MY_SECRET_P4SS
  port: 6379
  sessionEnabled: true
  sessionHost: redis
  sessionPersistentPolicies: DEFAULT  
  sslEnabled: false

database:
  image: pgvector/pgvector:pg16
  local: true
  storageSize: 3Gi
  host: postgres.local
  name: dotcms
  username: dotcmsdbuser
  password: password
  port: 5432
  maxConnections: 400
  sharedBuffers: 128MB

opensearch:
  image: opensearchproject/opensearch:1
  clusterName: elastic-cluster
  local: true
  storageSize: 3Gi
  host: opensearch.local
  port: 9200
  javaOpts: '-Xmx1G'
  ports:
    - 9200
    - 9600
