environment-type: staff-sandbox
cloud_provider: aws

aws:
  region: us-east-1
  serviceAccount:
    roleArn: ""
  secrets:
    secretsArn: ""

linkerd:
  enabled: true

database:
  local:
    enabled: false
  host: dotcms-internal.cafdyqpndbn1.us-east-1.rds.amazonaws.com
  #name: sbolton_auth_db

opensearch:
  local:
    enabled: false
  host: internal-2-es.dotcms.cloud
  port: 443
  protocol: https
redis:
  local:
    enabled: false
  host: dotcms-redis.sbolton.0001.use1.cache.amazonaws.com
  port: 6379

mail:
  enabled: true
  host: email-smtp.us-east-1.amazonaws.com
  port: 587

secrets:
  useSecretsStoreCSI: true
  createSecrets: false

dotcms:
  imagePullPolicy: Always
  redisSessions:
    enabled: false
  opensearch:
    host: internal-2-es.dotcms.cloud
    port: 443
  ingress:
    hostSuffix: dotcms.cloud
    type: alb
    alb:
      certificateArn: ""
      sslPolicy: ""
      securityGroups: ""
  affinity:
    requireDifferentHosts: true
  resources:
    requests:
      cpu: 0.5
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi

environments:
  prod:
    dotcms:
      enabled: true
      replicas: 1
      mapToTopLevelDomain: false