namespace: dotcms-dev
# Operation to perform: "backup" or "restore"
operation: backup
# Jobs configuration
jobRetries: 3
ttlSecondsAfterFinished: 900 # 1/4 hour

# List of PVCs to backup/restore
dotcmsClusterPvcs:
  - database-pvc
  - dotcms-pvc
  - opensearch-pvc

# Backup configuration
backupJobName: backup-job
backupFileName: backup-complete.tar.gz
backupPvcName: backup-pvc
backupPvcSize: 5Gi
backupOutputPath: /backup
backupHostPath: /private/tmp
# backupStorageClassName: hostpath

# Restore configuration
restoreJobName: restore-job
restoreFileName: backup-complete.tar.gz
restoreHostPath: /private/tmp