{{- if eq .Values.operation "backup" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job-{{ now | date "20060102-150405" }}
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: {{ .Values.retries }}
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: backup
          image: busybox
          command:
            - sh
            - -c
            - >
              echo "Starting backup...";
              BACKUP_DIR="/backup";
              mkdir -p $BACKUP_DIR;
              
              TEMP_DIR="/tmp/backup-temp";
              mkdir -p $TEMP_DIR;

              {{- range .Values.pvcList }}
              echo "Creating archive for /mnt/{{ . }}...";
              tar czf $TEMP_DIR/{{ . }}.tar.gz -C /mnt/{{ . }} . || exit 1;
              {{- end }}

              echo "Combining all archives into one...";
              tar czf $BACKUP_DIR/{{ .Values.fileName }}.tar.gz -C $TEMP_DIR . || exit 1;

              echo "Cleanup temporary files...";
              rm -rf $TEMP_DIR;

              echo "Backup completed at $BACKUP_DIR/{{ .Values.fileName }}.tar.gz";      
          volumeMounts:
            {{- range .Values.pvcList }}
            - name: {{ . }}
              mountPath: /mnt/{{ . }}
            {{- end }}
            - name: backup-volume
              mountPath: /backup
      volumes:
        {{- range .Values.pvcList }}
        - name: {{ . }}
          persistentVolumeClaim:
            claimName: {{ . }}
        {{- end }}
        - name: backup-volume
          hostPath:
            path: {{ .Values.hostPath }}
            type: DirectoryOrCreate
{{- end }}            