{{- if eq .Values.operation "restore" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "restore-job-{{ now | date "20060102-150405" }}"
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: {{ .Values.retries }}
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: restore
        image: busybox
        command:
          - sh
          - -c
          - >
            echo "Starting restore process...";
            RESTORE_FILE="/restore/{{ .Values.fileName }}.tar.gz";
            if [ ! -f $RESTORE_FILE ]; then
              echo "Error: Backup file $RESTORE_FILE not found!";
              exit 1;
            fi;

            echo "Extracting backup from $RESTORE_FILE...";
            mkdir -p /tmp/restore-temp;
            tar xzf $RESTORE_FILE -C /tmp/restore-temp || exit 1;

            {{- range .Values.pvcList }}
            echo "Restoring content to /mnt/{{ . }}...";
            tar xzf /tmp/restore-temp/{{ . }}.tar.gz -C /mnt/{{ . }} || exit 1;
            {{- end }}

            ls -lthR /tmp/restore-temp;
            
            echo "Restore process completed successfully!";            

        volumeMounts:
          {{- range .Values.pvcList }}
          - name: {{ . }}
            mountPath: /mnt/{{ . }}
          {{- end }}
          - name: restore-volume
            mountPath: /restore          
      volumes:
        {{- range .Values.pvcList }}
        - name: {{ . }}
          persistentVolumeClaim:
            claimName: {{ . }}
        {{- end }}
        - name: restore-volume
          hostPath:
            path: {{ .Values.hostPath }}
            type: Directory        
{{- end }}
