name: Lint and Test Helm Chart

on:
  workflow_call:

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      # 3. Set up Python (required by chart-testing tools)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 4. Set up chart-testing
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      # 5. Run chart-testing to list changed charts
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # 6. Run chart-testing to lint charts
      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml
  
      # # 7. Create kind cluster  
      # - name: Create kind cluster
      #   uses: helm/kind-action@v1
      #   if: steps.list-changed.outputs.changed == 'true'

      # # 8. Create a custom namespace
      # - name: Create custom namespace
      #   run: |
      #     kubectl create namespace dotcms-dev        
      #   if: steps.list-changed.outputs.changed == 'true'

      # # 9. Run chart-testing to install charts
      # - name: Run chart-testing (install)
      #   run: ct install --config ct.yaml
